REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{schema}} FROM {{ai_role}};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{schema}} FROM {{ai_role}};
REVOKE ALL PRIVILEGES ON SCHEMA {{schema}} FROM {{ai_role}};
